services:
  - type: web
    name: eduwingz-backend
    runtime: python
    buildCommand: bash build.sh
    startCommand: cd backend/backend && gunicorn backend.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        sync: false
      - key: ALLOWED_HOSTS
        value: "*.onrender.com,localhost"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://eduwingz.vercel.app,http://localhost:3000"
