services:
  - type: web
    name: eduwingz-backend
    runtime: python
    rootDir: backend/backend
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --no-input
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        sync: false
      - key: ALLOWED_HOSTS
        value: "eduwingz-backend.onrender.com, localhost"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://eduwingz.vercel.app, http://localhost:3000"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://eduwingz.vercel.app, https://eduwingz-backend.onrender.com"
