databases:
  - name: eduwingz_db
    engine: postgres
    version: "15"
    plan: free

services:
  - type: web
    name: eduwingz-backend
    runtime: python
    buildCommand: bash ../../build.sh
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: eduwingz_db
          property: connectionString
